name: Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

    paths-ignore:
      - ".*/**"
      - "!.github/workflows/pull_request.yaml"
      - "vscode/**"
      - ".env.example"
      - "LICENSE"
      - "*.md"

jobs:
  quality:
    name: Quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Yarn install with caching
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: yarn run lint:ci

      - name: Test
        run: yarn test --ci --colors --collectCoverage
