name: Run Tests

on:
  push:
    paths:
      - "**.[jt]s"
      - "package.json"
      - "yarn.lock"
      - "tsconfig.json"
      - ".github/workflows/testing.yaml"

  pull_request:
    paths:
      - "**.[jt]s"
      - "package.json"
      - "yarn.lock"
      - "tsconfig.json"
      - ".github/workflows/testing.yaml"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Yarn install with caching
        uses: bahmutov/npm-install@v1

      - name: Run tests with coverage
        run: yarn test --ci --colors --collectCoverage
